_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  # META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedRCNN"
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  # RPN:
  #   POSITIVE_FRACTION: 0.25
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "CrossEntropy" # variant: "CrossEntropy"
    NUM_CLASSES: 1 # original number 
    OLD_CLASSES: ["Model 24"
                      ]
    NEW_CLASSES: ["Model 24"
                      ]   

  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
SOLVER:
  LR_SCHEDULER_NAME: "LRMultiplier" # was "WarmupTwoStageMultiStepLR"
  STEPS: (60000, 80000, 90000, 360000)
  FACTOR_LIST: (1, 1, 1, 1, 1)
  MAX_ITER: 50000 #was 360000, tested with 150000, also check https://stackoverflow.com/questions/63578040/how-many-images-per-iteration-in-detectron2
  IMG_PER_BATCH_LABEL: 1
  IMG_PER_BATCH_UNLABEL: 1
  BASE_LR: 0.0008 # 0.001 worked on stable version
  WEIGHT_DECAY: 0.0001 # was 0.0001 before
DATASETS:
  TRAIN_LABEL: ("tless_rendered_trainval",)
  #("voc_2012_trainval",) #voc_2012_train
  # TRAIN_UNLABEL: ("voc_2012_val",) #Clipart1k_train
  # TEST: ("voc_2012_val",) #Clipart1k_test
  TRAIN_UNLABEL: ("tless_real_trainval",)
  #("Clipart1k_train",) #Clipart1k_train
  TEST: ("tless_real_test",)
  #("Clipart1k_test",) #Clipart1k_test
SEMISUPNET:
  Trainer: "ateacher"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 1
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 1.0
  DIS_TYPE: "res4" #["concate","p2","multi"]
TEST:
  EVAL_PERIOD: 1000